#!/usr/bin/env bash
set -euo pipefail

# preToolUse (Write|StrReplace): deny hand-edits to generated Prismic types.
# src/prismic/types/prismic.generated.ts is produced by `pnpm types:prismic`.

source "$(dirname "$0")/_lib.sh"
hook_input

file="$(tool_file_path)"

case "$file" in
  */src/prismic/types/* | src/prismic/types/*) ;;
  *) exit 0 ;;
esac

reason="Blocked: src/prismic/types/ is generated by \`pnpm types:prismic\` and must not be hand-edited. If a Prismic custom type changed, the user regenerates the types, then you update the consumers. See docs/handbook/prismic.md."

deny_tool "$reason"
exit 0
